language: node_js
sudo: required
dist: trusty
group: bluezone
node_js:
- 12.4.0
services:
- docker
env:
  global:
  - IMAGE="icr.io/wazi-code/ibm-wazi-developer-for-workspaces-codeready"
before_install: 
  - curl https://public.dhe.ibm.com/ibmdl/export/pub/software/htp/zos/tools/wazi/wazi-development-client-1.0.x-20200909.zip | jar xv ibm-rse-api-for-zowe-cli-1.0.1.tgz
  - mv ibm-rse-api-for-zowe-cli-1.0.1.tgz ibm-rse-api-for-zowe-cli.tgz
install: docker build -t ${IMAGE}:travis .
script: echo "Success!"
notifications:
  slack: ibm-systems-z:kiD2FZtJUJtUSp57dwHWwNX1
